name: ms-data
channels:
  - conda-forge
  - nodefaults
dependencies:
  # ---- Core ----
  - python=3.11.14
  - numpy<=2.26
  - pandas
  - scipy
  - h5py
  - pyyaml

  # ---- Visualization / Jupyter ----
  - matplotlib
  - seaborn
  - pyvista
  - jupyterlab
  - ipykernel

  # ---- Domain packages (from conda-forge) ----
  - pyiron_workflow=0.15.4
  - pympipool=0.9.1
  - executorlib=1.7.2
  - orix
  - damask   # installs DAMASK (python package) from conda-forge 

  # ---- Install latest Kanapy and damask_python from GitHub/ICAMS via pip ----
  - pip
  - pip:
      - git+https://github.com/ICAMS/Kanapy.git
      - git+https://github.com/ICAMS/damask_python.git

